name: wasm_interop
version: 1.0.0-dev.0.0
description: Dart wrapper for WebAssembly JavaScript API
author: Alexey Knyazev
homepage: https://github.com/lexaknyazev/wasm.dart
documentation:

environment:
  sdk: '>=2.0.0-dev.68 <3.0.0'

dependencies:
  js: ^0.6.1
  meta: ^1.1.5

dev_dependencies:
  build_runner: ^0.9.1
  build_test: ^0.10.3
  build_web_compilers: ^0.4.0
  build_node_compilers: ^0.1.8
  test: ^1.2.0
