name: wasm_interop
version: 2.0.1
description: This package provides a Dart wrapper for WebAssembly JavaScript API
homepage: https://github.com/lexaknyazev/wasm.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3
  meta: ^1.7.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  test: ^1.17.10
