name: wasm_interop
version: 1.0.0-dev.1.0
description: Dart wrapper for WebAssembly JavaScript API
author: Alexey Knyazev
homepage: https://github.com/lexaknyazev/wasm.dart
documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^1.12.2
  test: ^1.16.8
