name: wasm_interop
version: 1.0.0-dev.1.0
description: Dart wrapper for WebAssembly JavaScript API
author: Alexey Knyazev
homepage: https://github.com/lexaknyazev/wasm.dart
documentation:

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  js: ^0.6.1
  meta: ^1.1.5

dev_dependencies:
  build_runner: ^1.2.0
  build_test: any
  build_web_compilers: ^1.0.0
  build_node_compilers: ^0.2.1
  test: ^1.5.2
